name: Pages CI

on:
  push:
    branches:
      - Deepan
  pull_request:
    branches:
      - Deepan

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PyTest
        run: pytest -v -m "smoke"